Simgun/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

from product.models import Product
from ketabkhor import views


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')


class BookSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Product
        fields = ('isbn', 'title', 'author', 'translator')


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class BookViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = BookSerializer


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'product', BookViewSet)

urlpatterns = [
    url(r'^$', views.home_page, name='home_page'),
    url(r'^admin/', admin.site.urls),
    url(r'^product/', include('product.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^profiles/', include('profiles.urls')),
    url(r'^vendors/', include('vendors.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^premium/', include('premium.urls')),
    url(r'^vendors/', include('vendors.urls')),
    url(r'^orders/', include('buying.urls')),
    url(r'^api/', include(router.urls)),
    url(r'^api/v1/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^support/', include('support.urls'))
]

accounts/urls.py
from django.conf.urls import url

from accounts import views

app_name = 'accounts'
urlpatterns = [
    url(r'^register/$', views.user_register, name='user_register'),
    url(r'^login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
]

profiles/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from profiles import views

app_name = 'profiles'
urlpatterns = [
    url(r'^(?P<profile_id>[0-9]+)/$', login_required(views.profile),
        name='profile'),
    url(r'^(?P<profile_id>[0-9]+)/settings/$', login_required(views.settings),
        name='settings'),
    url(r'^(?P<profile_id>[0-9]+)/upgrade/$', login_required(views.upgrade_user),
        name='upgrade_user'),
    url(r'^(?P<profile_id>[0-9]+)/wishlists/$', login_required(views.wishlist),
        name='wishlist'),

    url(r'^(?P<profile_id>[0-9]+)/shoppingbag/$', login_required(views.shoppingbag),
        name='shoppingbag'),
    url(r'^(?P<profile_id>[0-9]+)/shoppingbag/(?P<bag_id>[0-9]+)/$', login_required(views.shoppingbag_spec),
        name='shoppingbag_spec'),

    url(r'^(?P<profile_id>[0-9]+)/shoppingbag/add/$', login_required(views.add_to_shoppingbag),
        name='add_shoppingbag'),

    url(r'^(?P<profile_id>[0-9]+)/shoppingbag/setaddress/', login_required(views.set_address),
        name='set_address'),
    url(r'^(?P<profile_id>[0-9]+)/shoppingbag/complete/', login_required(views.comp_shopp),
        name='comp_shopping'),
    url(r'^(?P<profile_id>[0-9]+)/shoppingbag/changestate/', login_required(views.shoppingbag_change_state),
        name='shoppingbag_change_state_url'),
    url(r'^(?P<profile_id>[0-9]+)/reviews/$', login_required(views.reviews),
        name='reviews'),
    url(r'^(?P<profile_id>[0-9]+)/reviews/(?P<review_id>[0-9]+)/remove/$', login_required(views.remove_review),
        name='remove_review'),

]

search/urls.py
from django.conf.urls import url

from search import views

app_name = 'search'
urlpatterns = [
    url(r'^', views.search, name='search'),
]

vendors/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from vendors import views

app_name = 'vendors'
urlpatterns = [
    url('^(?P<vendor_id>[0-9]+)/$', login_required(views.vendor_profile), name='vendor_profile'),
    url('^(?P<vendor_id>[0-9]+)/add-book/$', login_required(views.add_product), name='add_product'),
    url('^(?P<vendor_id>[0-9]+)/orders/$', login_required(views.vendor_orders), name='vendor_orders'),
]

Simgun/models.py
from django.db import models

from product.models import Product


class MainShowcase(models.Model):
    img = models.ImageField(upload_to='static/site-media/photos/profiles/', null=False)
    book = models.OneToOneField(Product, on_delete=models.CASCADE)

templates/simgun/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %} {% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'general/css/semantic/semantic.css' %}"/>
    <link rel="stylesheet" href="{% static 'general/css/generic-style.css' %}"/>

    {% block styles %}
    {% endblock %}

    <script type="text/javascript" src="{% static 'general/js/jquery-3.1.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'general/js/semantic.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'general/js/generic-script.js' %}"></script>
    <script type="text/javascript" src="{% static 'general/js/header-footer.js' %}"></script>


</head>
<body>

<!-- header -->
<header class="header1">
    <div class="ui menu back-grey-menu no-borders">
        <div class="ui grid container ">
            <div class="ten wide column right aligned">
                <div class="ui row row-margin1">
            <span>فروشگاه اینترنتی زنبیل ،
                {% if user.is_authenticated %}
                    سلام {{ user.first_name }} {{ user.last_name }} !
                    <a href="/accounts/logout/">(خروج)</a>
                {% else %}
                    <a href="{% url 'accounts:user_register' %}">ثبت نام کنید</a>
                    یا
                    <a href="{% url 'accounts:user_login' %}">وارد شوید</a>
                {% endif %}
            </span>

                </div>
                <div class="ui row row-margin2">
                    <div class="ui search">
                        <div class="ui simple scrolling fluid search left icon input search-tab">
                            <i class="search icon"></i>
                            <input id="search-bar" class="prompt" style="text-align: right" type="text" placeholder="جستجو">
                        </div>
                        <div class="results"></div>
                    </div>
                </div>
            </div>
            <div class="two wide column center aligned">
{#                <h2 class="logo">فروشگاه</h2>#}
            </div>
            <div class="four wide column center aligned">
                <a href="{% url 'home_page' %}">
                    <img class="logo-img" src="{% static 'site-media/photos/general/logo.png' %}">
                </a>
            </div>

        </div>
    </div>
    <div class="ui menu  no-borders " id="menu2">
        <div class="ui container">
            <a class="green header link item"
             {% if user.userprofile %}
                href="{% url 'profiles:shoppingbag' user.id %}"
            {% endif %}
            >
                <i class="shop icon"></i>
                سبد خرید
            </a>



{% for c in mainCategories %}
            <a class=" red link item" href="{% url 'search:search' %}?category={{ c }}">
              {{ c }}
            </a>
{% endfor %}


        </div>
    </div>

</header>


{% block content %}
{% endblock %}


<footer class="site-footer">
    <div class="ui vertical footer segment">
        <div class="ui center aligned container">
            <div class="ui  four column grid ">
                <div class="ui row">
                    <div class="three wide right aligned column">
                        <div class="ui animated large relaxed link right aligned list">
                            <h4 class="header bold" style="text-align: right">منو ها</h4>
                            </hr>
                            <a href="{% url 'home_page' %}" class="item">خانه</a>
                            {% if user.is_authenticated %}
                                <a class="item" id="support-button">تیکت پشتیبانی</a>
                            {% endif %}
                            <a class="item">قوانین</a>
                        </div>
                    </div>
                    <div class="three wide right aligned column">
                        <div class="ui animated large relaxed link right aligned list">

                            <h4 class="header bold"> پروفایل شما</h4>
                            </hr>
                            {% if user.is_authenticated %}
                                {% if user.userprofile %}
                                    <a href="{% url 'profiles:profile' user.userprofile.id %}"
                                       class="item">حساب کاربری
                                    </a>
                                    <a class="item">سبد خرید</a>

                                {% elif user.vendor %}
                                    <a href="{% url 'vendors:vendor_profile' user.vendor.id %}"
                                       class="item">حساب ارائه‌دهنده</a>

                                {% elif user.supportagent %}
                                    <a href="{% url 'vendors:vendor_profile' user.supportagent.id %}"
                                       class="item">صفحه تیکت ها</a>

                                {% endif %}
                            {% else %}
                                <a class="item" href="{% url 'accounts:user_login' %}">ورود</a>
                                <a class="item" href="{% url 'accounts:user_register' %}">ثبت نام</a>
                            {% endif %}
                        </div>
                    </div>

                    <div class="four wide right aligned column" >

                    </div>
                    <div class="six wide right aligned column">
                        <h4 class="header">درباره ما</h4>
                        <div>
                            <p>
سایت زنبیل حاصل تلاش بیش از یک ماه می باشد که برای پروژه درس دیتابیس آماده سازی شده است .
                               بخشی از امکانات با توجه به زمان تکمیل نشده است اما در کل تمامی بخش های مدل ER را پوشش می دهد .
                                پروژه درس دیتابیس | استاد جناب آقای دکتر زارع پور | بهار و تابستان ۱۳۹۶
| دانشگاه صنعتی شریف
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="ui vertical footer2 segment">
        <div class="ui center aligned container">
            <div class="ui grid container">
                <div class="ten wide column right aligned">
                </div>
                <div class="six wide column right aligned">
                    <h5 class="ui header copyright" >Copyright © 2017 Zanbeel</h5>
                </div>
            </div>
        </div>
    </div>
</footer>


{% if user.is_authenticated %}
    <div class="ui modal" id="support-modal">
        <i class="close icon"></i>
        <div class="header">
            تیکت پشتیبانی
        </div>
        <div class=" content">
            <div class="content-margin">
            </div>
            <span></span>
            <div class="description">
                <form class="ui form">
                    <div class="three fields">
                        <div class="required field">
                            <label>عنوان</label>
                            <input type="text" placeholder="">
                        </div>
                    </div>
                    <div class="field">
                        <div class="sixteen wide required field">
                            <label>متن جواب تیکت</label>
                            <textarea type="text" ></textarea>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="actions">
            <div class="ui orange button">ارسال</div>
            <div class="ui inverted grey button " id="ticket-cancel">بازگشت</div>
        </div>
    </div>
{% endif %}

{% block scripts %}
{% endblock %}


</body>
</html>