Simgun/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

from product.models import Product
from ketabkhor import views


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')


class BookSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Product
        fields = ('isbn', 'title', 'author', 'translator')


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class BookViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = BookSerializer


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'product', BookViewSet)

urlpatterns = [
    url(r'^$', views.home_page, name='home_page'),
    url(r'^admin/', admin.site.urls),
    url(r'^product/', include('product.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^profiles/', include('profiles.urls')),
    url(r'^vendors/', include('vendors.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^premium/', include('premium.urls')),
    url(r'^vendors/', include('vendors.urls')),
    url(r'^orders/', include('buying.urls')),
    url(r'^api/', include(router.urls)),
    url(r'^api/v1/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^support/', include('support.urls'))
]

premium/urls.py
from django.conf.urls import url

from premium import views

app_name = 'premium'
urlpatterns = [
    url(r'^$', views.premium, name='premium'),
]

product/urls.py
from django.conf.urls import url

from product import views


app_name = 'product'
urlpatterns = [
    url(r'^(?P<p_id>[0-9]+)/$', views.product_details, name='productDetailsUrl'),
    url(r'^(?P<p_id>[0-9]+)/review/add/$', views.add_book_review, name='addProductReviewUrl'),
    url(r'^(?P<p_id>[0-9]+)/rate/add/$', views.rate_book, name='addProductRateUrl'),
]

search/urls.py
from django.conf.urls import url

from search import views

app_name = 'search'
urlpatterns = [
    url(r'^', views.search, name='search'),
]

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.db.models import Q
from django.http import Http404
from django.shortcuts import render

from product.models import Product


def search(request):
    # try:
    title, results, query = advanced_search(request)
    # except Exception:
    #     raise Http404

    if not results:
        return render(request, 'search/advanced-search-404.html', {
            'title': title})

    return render(request, 'search/advanced-search.html', {
        'title': title,
        'products': results,
        'form_data': query
    })


def advanced_search(request):
    # It's easier to store a dict of the possible lookups we want, where
    # the values are the keyword arguments for the actual query.

    query = build_advance_search_query(request)

    title = ""
    # return empty result for empty query
    if len(query) == 0:
        return [], [], []

    # select one of two approaches for search, by params or best guess
    if 'best' in query:
        title = query['best']
        search_results = search_by_best_guess(query)
    else:
        # get first item in query as title
        title = next(iter(query.values()))

        search_results = search_by_params(query)

    return title, search_results, query


def build_advance_search_query(request):
    """Returns a modified copy of request.GET that has no empty value"""
    query = request.GET.copy()
    candidate_queries = {'q', 'description', 'category', 'best', 'max_price', 'min_price'}
    # normalize query
    for q in list(query):
        value = query[q]
        value = value.strip()
        if not value:
            del query[q]
        if q not in candidate_queries:
            del query[q]
        else:
            query[q] = value

    return query


def search_by_best_guess(query):
    best = query['best']
    # try:
    #     isbn = int(best)
    #     return Product.objects.filter(isbn__exact=isbn)
    # except ValueError:
    return Product.objects.filter(Q(title__contains=best).__or__(Q(description__contains=best)))


def search_by_params(query):
    qdict = {'q': 'title__contains',
             'description': 'description__contains',
             'category': 'category__title__contains',
             }
    # Then we can do this all in one step instead of needing to call
    # 'filter' and deal with intermediate data structures.
    q_objs = [Q(**{qdict[k]: query[k]}) for k in qdict.keys() if k in query]
    search_results = Product.objects.select_related().filter(*q_objs)

    if 'min_price' in query and 'max_price' in query:
        search_results = search_results.filter(price__range=(query['min_price'], query['max_price']))
    elif 'min_price' in query:
        search_results = search_results.filter(price__gte=query['min_price'])
    elif 'max_price' in query:
        search_results = search_results.filter(price__lte=query['max_price'])

    return search_results

templates/search/advanced-search-404.html
{% extends './searchBase.html' %}

{% block noResults %}
    <div class="ui grid container center aligned row-margin1">
            <h2>متاسفانه نتیجه ای برای عبارت "{{ title }}" یافت نشد!</h2>
        </div>
{% endblock %}

{% block scripts %}
    <script>

        $("#submit_search_form").click(function () {

            var nonEmptyFields = $('#search_form').find(':input').filter(function () {
                return $(this).val().length == 0
            }).length;

            if (nonEmptyFields === 7) {
                $('#search_form').attr('onsubmit', 'return false;');
                alert("لطفا حداقل یک فیلد را پر کنید");

            } else {
                $('#search_form').attr('onsubmit', 'return true;');
                $('#search_form').find(':input').each(function () {
                    if ($(this).val() == '') {
                        $(this).remove();
                    }
                });
                $("#search_form").submit(function () {
                    return true;
                });
            }
        });

    </script>
    <script>
        $(function () {
            $('.ui.rating')
                .rating({
                    initialRating: 0,
                    maxRating: 5
                })
            ;
            $('#rate-star')
                .rating('setting', 'clearable', true)
            ;
            $('#rate-star2')
                .rating({
                    initialRating: 3,
                    maxRating: 5
                })
                .rating('disable')
            ;
            $('.ui.dropdown')
                .dropdown()
            ;
            $('.special.cards .image').dimmer({
                on: 'hover'
            });
        })
    </script>
    <script type="text/javascript">
        $('.ui.radio.checkbox')
            .checkbox()
        ;

    </script>

{% endblock %}

templates/search/advanced-search.html
{% extends './searchBase.html' %}

{% block results %}
    <div class="ui grid container center aligned">
            <!-- Book Result-->
            <div class="ui row">
                <div class="twelve wide column right aligned">
                    <div class="title search">
                        <h2>نتایج</h2>
                    </div>
                    <div class="ui divider tab-divider"></div>
                    <div class="ui grid container">
                        <div class="ui row">
                            {% for book in products %}
                                <div class="three wide column">
                                    <div class="ui link special cards">
                                        <div class="red card">
                                            <div class="blurring dimmable image">
                                                <div class="ui inverted dimmer">
                                                    <div class="content">
                                                        <div class="center">
                                                            <a href="{% url 'product:productDetailsUrl' book.id %}">
                                                                <div class="ui inverted button">مشاهده</div>
                                                            </a>
                                                        </div>
                                                    </div>
                                                </div>
                                                <img src="/{{ book.mainPic }}">
                                            </div>
                                            <div class="content">
                                                <a class="header"
                                                   href="{% url 'product:productDetailsUrl' book.id %}">{{ book.title }}</a>
                                                <div class="meta"> {{ book.author }}</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="ui row">
                            <div class="left column left aligned">
                                <button class="ui grey inverted button link">نمایش بیشتر</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
{#            <!-- PDF Result-->#}
{#            <div class="ui row">#}
{#                <div class="twelve wide column right aligned">#}
{#                    <div class="title search">#}
{#                        <h2>کتاب رقمی</h2>#}
{#                    </div>#}
{#                    <div class="ui divider tab-divider"></div>#}
{#                    <div class="ui grid container">#}
{#                        <div class="ui row">#}
{#                            <a href="{% url 'premium:premium' %}">برای دسترسی به این قسمت باید کاربر طلایی باشید</a>#}
                            {#                        <div class="three wide column">#}
                            {#                            <div class="ui link special cards">#}
                            {#                                <div class="red card">#}
                            {#                                    <div class="blurring dimmable image">#}
                            {#                                        <div class="ui inverted dimmer">#}
                            {#                                            <div class="content">#}
                            {#                                                <div class="center">#}
                            {#                                                    <div class="ui inverted button">مشاهده</div>#}
                            {#                                                </div>#}
                            {#                                            </div>#}
                            {#                                        </div>#}
                            {#                                        <img src="img/516GyHY9p6L.jpg">#}
                            {#                                    </div>#}
                            {#                                    <div class="content">#}
                            {#                                        <a class="header" href="#">نام کتاب</a>#}
                            {#                                        <div class="meta"> توسط ...</div>#}
                            {#                                    </div>#}
                            {#                                </div>#}
                            {#                            </div>#}
                            {#                        </div>#}
{#                        </div>#}
                        {#                    <div class="ui row">#}
                        {#                        <div class="left column left aligned">#}
                        {#                            <button class="ui grey inverted button link">نمایش بیشتر</button>#}
                        {#                        </div>#}
                        {#                    </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#            <!-- Sound Result-->#}
{#            <div class="ui row">#}
{#                <div class="twelve wide column right aligned">#}
{#                    <div class="title search">#}
{#                        <h2>کتاب صوتی</h2>#}
{#                    </div>#}
{#                    <div class="ui divider tab-divider"></div>#}
{#                    <a href="{% url 'premium:premium' %}">برای دسترسی به این قسمت باید کاربر طلایی باشید</a>#}
{##}
                    {#                <div class="ui grid container">#}
                    {#                    <div class="ui row">#}
                    {#                        <div class="three wide column">#}
                    {#                            <div class="ui link special cards">#}
                    {#                                <div class="red card">#}
                    {#                                    <div class="blurring dimmable image">#}
                    {#                                        <div class="ui inverted dimmer">#}
                    {#                                            <div class="content">#}
                    {#                                                <div class="center">#}
                    {#                                                    <div class="ui inverted button">مشاهده</div>#}
                    {#                                                </div>#}
                    {#                                            </div>#}
                    {#                                        </div>#}
                    {#                                        <img src="img/516GyHY9p6L.jpg">#}
                    {#                                    </div>#}
                    {#                                    <div class="content">#}
                    {#                                        <a class="header" href="#">نام کتاب</a>#}
                    {#                                        <div class="meta"> توسط ...</div>#}
                    {#                                    </div>#}
                    {#                                </div>#}
                    {#                            </div>#}
                    {#                        </div>#}
                    {#                    </div>#}
                    {#                    <div class="ui row">#}
                    {#                        <div class="left column left aligned">#}
                    {#                            <button class="ui grey inverted button link">نمایش بیشتر</button>#}
                    {#                        </div>#}
                    {#                    </div>#}
                    {#                </div>#}
{#                </div>#}
{#            </div>#}
        </div>
{% endblock %}

{% block scripts %}
    <script>

        $("#submit_search_form").click(function () {

            var nonEmptyFields = $('#search_form').find(':input').filter(function () {
                return $(this).val().length == 0
            }).length;

            if (nonEmptyFields === 7) {
                $('#search_form').attr('onsubmit', 'return false;');
                alert("لطفا حداقل یک فیلد را پر کنید");

            } else {
                $('#search_form').attr('onsubmit', 'return true;');
                $('#search_form').find(':input').each(function () {
                    if ($(this).val() == '') {
                        $(this).remove();
                    }
                });
                $("#search_form").submit(function () {
                    return true;
                });
            }
        });

    </script>
    <script>
        $(function () {
            $('.ui.rating')
                .rating({
                    initialRating: 0,
                    maxRating: 5
                })
            ;
            $('#rate-star')
                .rating('setting', 'clearable', true)
            ;
            $('#rate-star2')
                .rating({
                    initialRating: 3,
                    maxRating: 5
                })
                .rating('disable')
            ;
            $('.ui.dropdown')
                .dropdown()
            ;
            $('.special.cards .image').dimmer({
                on: 'hover'
            });
        })
    </script>
    <script type="text/javascript">
        $('.ui.radio.checkbox')
            .checkbox()
        ;

    </script>

{% endblock %}

templates/search/searchBase.html
{% extends 'simgun/base.html' %}

{% block title %}
    <title>زنبیل |‌ جستجو برای {{ title }}</title>
{% endblock %}

{% block styles %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'search/css/style-search.css' %}"/>
{% endblock %}

{% block content %}
    <div class="ui container search-margin">

    {% block noResults %}

{% endblock %}

        <!-- Search Box-->
        <form id="search_form" class="ui grid container centered aligned" method="get">
            <div class="twelve wide column right aligned back-grey">
                <div class="ui grid container">
                    <div class="ui row">
                        <h2 class="ui header">جستجو برای عبارت "{{ title }}"</h2>
                    </div>
                    <div class="ui divider tab-divider"></div>
                    <!-- Search Form -->
                    <div class="ui row">
                        <!-- Right Column -->
                        <div class="eight wide column">
                            <div class="ui form">
                                <div class="inline fields">
                                    <div class="five wide field">
                                        <label for="title">نام محصول</label>
                                    </div>
                                    <div class="eleven wide field">
                                        <input id="title" name="q" type="text" value=""/>
                                    </div>
                                </div>
                                <div class="inline fields">
                                    <div class="five wide field">
                                        <label for="author">توضیحات</label>
                                    </div>
                                    <div class="eleven wide field">
                                        <input name="description" id="description" type="text" value=""/>
                                    </div>
                                </div>
{#                                <div class="inline fields">#}
{#                                    <div class="five wide field">#}
{#                                        <label for="translator">مترجم</label>#}
{#                                    </div>#}
{#                                    <div class="eleven wide field">#}
{#                                        <input name="translator" id="translator" type="text" value="">#}
{#                                    </div>#}
{#                                </div>#}
                            </div>
                        </div>
                        <!-- Left Column -->
                        <div class="eight wide column right aligned">
                            <div class="ui form">
                                <div class="inline fields">
                                    <div class="five wide field">
                                        <label for="category">دسته بندی</label>
                                    </div>
                                    <div class="eleven wide field">
                                        <input name="category" id="category" type="text" value="">
                                    </div>
                                </div>

{#                                <div class="inline fields">#}
{#                                    <div class="five wide field">#}
{#                                        <label for="isbn">شابک/ISBN</label>#}
{#                                    </div>#}
{#                                    <div class="eleven wide field">#}
{#                                        <input name="isbn" id="isbn" type="text" value="">#}
{#                                    </div>#}
{#                                </div>#}
                            </div>
                        </div>
                    </div>
                    <!-- Price Range-->
                    <div class="ui row">
                        <div class="full wide column">
                            <div class="ui form">
                                <div class="inline fields">
                                    <div class="two wide field">
                                        <label for="min_price">محدوده قیمت</label>
                                    </div>
                                    <div class="five wide field">
                                        <input name="min_price" id="min_price" title="text" value="">
                                    </div>
                                    <div class="one wide field">
                                        <h5>تا</h5>
                                    </div>
                                    <div class="five wide field">
                                        <input name="max_price" id="max_price" title="text" value="">
                                    </div>
                                    <div class="one wide field">
                                        <h5>تومان</h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Book Type-->
{#                    <div class="ui row">#}
{#                        <div class="full wide column">#}
{#                            <div class="ui form">#}
{#                                <div class="inline fields">#}
{#                                    <div class="two wide field">#}
{#                                        <h5>نوع کتاب</h5>#}
{#                                    </div>#}
{#                                    <div class="three wide field">#}
{#                                        <div class="ui radio checkbox">#}
{#                                            <input type="radio" tabindex="0" class="hidden" name="book">#}
{#                                        </div>#}
{#                                        <span class="checkbox-label">کتاب کاغذی</span>#}
{#                                    </div>#}
{#                                    <div class="three wide field">#}
{#                                        <div class="ui radio checkbox">#}
{#                                            <input type="radio" tabindex="0" class="hidden" name="book">#}
{#                                        </div>#}
{#                                        <span class="checkbox-label">کتاب رقمی</span>#}
{#                                    </div>#}
{#                                    <div class="three wide field">#}
{#                                        <div class="ui radio checkbox">#}
{#                                            <input type="radio" tabindex="0" class="hidden" name="book">#}
{#                                        </div>#}
{#                                        <span class="checkbox-label">کتاب صوتی</span>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
                    <!-- search button -->
                    <div class="ui row">
                        <div class="left column left aligned">
                            <input id="submit_search_form" type="submit" class="ui button" tabindex="0" value="جستجو">
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <!-- Search Result-->
            {% block results %}

{% endblock %}


    </div>

{% endblock %}

{% block scripts %}
    <script>

        $("#submit_search_form").click(function () {

            var nonEmptyFields = $('#search_form').find(':input').filter(function () {
                return $(this).val().length == 0
            }).length;

            if (nonEmptyFields === 7) {
                $('#search_form').attr('onsubmit', 'return false;');
                alert("لطفا حداقل یک فیلد را پر کنید");

            } else {
                $('#search_form').attr('onsubmit', 'return true;');
                $('#search_form').find(':input').each(function () {
                    if ($(this).val() == '') {
                        $(this).remove();
                    }
                });
                $("#search_form").submit(function () {
                    return true;
                });
            }
        });

    </script>
    <script>
        $(function () {
            $('.ui.rating')
                .rating({
                    initialRating: 0,
                    maxRating: 5
                })
            ;
            $('#rate-star')
                .rating('setting', 'clearable', true)
            ;
            $('#rate-star2')
                .rating({
                    initialRating: 3,
                    maxRating: 5
                })
                .rating('disable')
            ;
            $('.ui.dropdown')
                .dropdown()
            ;
            $('.special.cards .image').dimmer({
                on: 'hover'
            });
        })
    </script>
    <script type="text/javascript">
        $('.ui.radio.checkbox')
            .checkbox()
        ;

    </script>

{% endblock %}