Simgun/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

from product.models import Product
from ketabkhor import views


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')


class BookSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Product
        fields = ('isbn', 'title', 'author', 'translator')


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class BookViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = BookSerializer


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'product', BookViewSet)

urlpatterns = [
    url(r'^$', views.home_page, name='home_page'),
    url(r'^admin/', admin.site.urls),
    url(r'^product/', include('product.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^profiles/', include('profiles.urls')),
    url(r'^vendors/', include('vendors.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^premium/', include('premium.urls')),
    url(r'^vendors/', include('vendors.urls')),
    url(r'^orders/', include('buying.urls')),
    url(r'^api/', include(router.urls)),
    url(r'^api/v1/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^support/', include('support.urls'))
]

buying/urls.py
from django.conf.urls import url

from buying import views

app_name = 'buying'

urlpatterns = [
    url(r'(?P<user_id>[0-9]+)/shopping/$', views.order_info, name='order_info'),
    url(r'(?P<user_id>[0-9]+)/addaddress/$', views.add_address, name='add_address'),
    url(r'(?P<user_id>[0-9]+)/removeaddress/(?P<add_id>[0-9]+)/$', views.order_info, name='remove_address'),

    url(r'(?P<user_id>[0-9]+)/getpostprice/$', views.get_post_price, name='get_post_price'),
    url(r'(?P<user_id>[0-9]+)/setpostprice/$', views.set_post_price, name='set_post_price'),
]

profiles/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from profiles import views

app_name = 'profiles'
urlpatterns = [
    url(r'^(?P<profile_id>[0-9]+)/$', login_required(views.profile),
        name='profile'),
    url(r'^(?P<profile_id>[0-9]+)/settings/$', login_required(views.settings),
        name='settings'),
    url(r'^(?P<profile_id>[0-9]+)/upgrade/$', login_required(views.upgrade_user),
        name='upgrade_user'),
    url(r'^(?P<profile_id>[0-9]+)/wishlists/$', login_required(views.wishlist),
        name='wishlist'),

    url(r'^(?P<profile_id>[0-9]+)/shoppingbag/$', login_required(views.shoppingbag),
        name='shoppingbag'),
    url(r'^(?P<profile_id>[0-9]+)/shoppingbag/(?P<bag_id>[0-9]+)/$', login_required(views.shoppingbag_spec),
        name='shoppingbag_spec'),

    url(r'^(?P<profile_id>[0-9]+)/shoppingbag/add/$', login_required(views.add_to_shoppingbag),
        name='add_shoppingbag'),

    url(r'^(?P<profile_id>[0-9]+)/shoppingbag/setaddress/', login_required(views.set_address),
        name='set_address'),
    url(r'^(?P<profile_id>[0-9]+)/shoppingbag/complete/', login_required(views.comp_shopp),
        name='comp_shopping'),
    url(r'^(?P<profile_id>[0-9]+)/shoppingbag/changestate/', login_required(views.shoppingbag_change_state),
        name='shoppingbag_change_state_url'),
    url(r'^(?P<profile_id>[0-9]+)/reviews/$', login_required(views.reviews),
        name='reviews'),
    url(r'^(?P<profile_id>[0-9]+)/reviews/(?P<review_id>[0-9]+)/remove/$', login_required(views.remove_review),
        name='remove_review'),

]

buying/models.py
from django.db import models

from accounts.models import UserProfile, Vendor
from product.models import Product


class PostPrice(models.Model):
    province = models.CharField(max_length=128)
    city = models.CharField(max_length=256)
    vendor = models.ForeignKey(Vendor)
    price = models.IntegerField(default=0)
    type_choices = ((0, 'پست'), (1, 'پیک'))
    type = models.BooleanField(choices=type_choices)

    cities = [
        ['تهران', ['تهران', 'شمیرانات', 'آزادی']],
        ['البرز', ['کرج', 'مصباح ', 'کرج']]
    ]

    def get_type_str(self):
        return self.type_choices[self.type][1]


class Address(models.Model):
    validity = models.BooleanField(default=1)
    province = models.CharField(max_length=128)
    city = models.CharField(max_length=256)
    phone_number = models.IntegerField(default=0)
    zipcode = models.IntegerField(default=0)
    address = models.CharField(max_length=1024)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=True, blank=True)

    def get_full_address(self):
        return str(self.province) + '-' + str(self.city) + '-' + str(self.address)

buying/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from accounts.models import UserProfile, Vendor

from buying.models import Address

from .models import PostPrice


def order_info(request, user_id):
    user_profile = get_object_or_404(UserProfile, user=request.user)
    adrs = user_profile.address_set.filter(validity=1).all()
    return render(request, 'buying/order-info.html', {"up": user_profile, 'adrs': adrs})


def get_post_price(request, user_id):
    vendor = get_object_or_404(Vendor, user=request.user)
    try:
        d = request.POST

        pp = vendor.postprice_set.filter(province=d['province'],
                            city=d['city'],
                            type=d['stype']).first()

        return JsonResponse({'stat': 1, 'price': pp.price})
    except:
        return JsonResponse({'stat': 0, 'price': 'این شهر قبلا ثبت نشده است.'})


def set_post_price(request, user_id):
    vendor = get_object_or_404(Vendor, user=request.user)
    try:
        d = request.POST

        pp = vendor.postprice_set.filter(province=d['province'],
                                         city=d['city'],
                                         type=d['stype'])

        if pp and pp.first():
            pp = pp.first()
            pp.price = d['price']
        else:
            pp = PostPrice(province=d['province'],
                           city=d['city'],
                           type=d['stype'],
                           vendor=vendor,
                           price=d['price']
                           )

        pp.save()
        return JsonResponse({'stat': 1})
    except:
        return JsonResponse({'stat': 0})


def add_address(request, user_id):
    # print(type(request.POST['city']))
    user_profile = get_object_or_404(UserProfile, user=request.user)
    try:
        d = request.POST
        address = Address(province=d['province'],
                          city=d['city'],
                          address=d['address'],
                          zipcode=d['zipcode'],
                          phone_number=d['phone_number'],
                          user_profile=user_profile)

        address.save()
        return JsonResponse({'stat': 1, 'add_id': address.id})
    except:
        return JsonResponse({'stat': 0})

templates/buying/order-info.html
{% extends 'books/../simgun/base.html' %}

{% block styles %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'buying/css/style-order-info.css' %}"/>

{% endblock %}

{% block title %}
    <title>زنبیل - اطلاعات سفارش</title>
{% endblock %}


{% block content %}

    <div class="ui container orderinfo-margin">
        <div class="ui one column grid orderinfo-grey">
            <div class="column">
                <h1 style="text-align: center"> اطلاعات شما برای سفارش</h1>
            </div>
            <div class="column">
                <div class="ui divider"></div>
                <h2>اطلاعات شما:</h2>
                <div class="ui hidden divider"></div>
            </div>
            <div class="ui two column grid">
                <div class="three wide column">
                    <h3>نام و نام خانوادگی: </h3>
                </div>
                <div class="column">
                    <p> {{ up }} </p>
                </div>
            </div>
            <div class="ui two column grid">
                <div class="one wide column">
                    <h3>ایمیل: </h3>
                </div>
                <div class="wide column">
                    <p>{{ up.user.email }}</p>
                </div>
            </div>
            <div class="ui two column grid">
                <div class="two wide column">
                    <h3>تلفن همراه: </h3>
                </div>
                <div class="column">
                    <p>khoodfdkfjl</p>
                </div>
                <div class="ui hidden divider"></div>
            </div>
            <div class="ui hidden divider"></div>
            <div class="column">
                <h2>انتخاب آدرس:</h2>
                <div class="ui hidden divider"></div>
            </div>

                <div id="oldAddresses" class="column"
                                     {% if adrs %}
                     style="display: block;"
                     {% else %}
                      style="display: none;"
                     {% endif %}
                >

                <div class="ui two column grid">
                    <div class="three wide column">
                        <h3>آدرس انتخاب شده: </h3>
                    </div>
                    <div class="thirteen wide column">
                        <div class="ui fluid dropdown selection">
                            <input type="hidden" name="selected_address">
                            <i class="dropdown icon"></i>
                            <div class="default text" id="addressPlaceHolder">آدرس</div>
                            <div class="menu" id="addressMenu">
                                {% for a in adrs %}
                                <div class="item" data-value="{{ a.id }}" style="direction: rtl"> {{ a.province }} - {{ a.city }} - {{ a.address }}</div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>


<div class="ui hidden divider"></div>
                <button class="ui left floated orange button" name="addNewAddress" value="Show Div" onclick="showDiv()">افزودن آدرس جدید</button>

        </div>
            <div class="column">

                <div class="ui one column grid" id="newaddressDiv"
                     {% if adrs %}
                     style="display: none;"
                     {% else %}
                      style="display: block;"
                     {% endif %}
                >
                    <div class="column">
                        <form class="ui form" action="" id="newAddressForm">
                            <h3><label>آدرس جدید</label></h3>
                            <div class="fields">
                                {% csrf_token %}
                                <div class="four wide field">
                                    <input type="text" name="province" placeholder="استان">
                                </div>
                                <div class="four wide field">
                                    <input type="text" name="city" placeholder="شهر">
                                </div>
                                <div class="four wide field">
                                    <input type="number" name="phone_number" placeholder="تلفن" onkeypress='validate_num(event)'>
                                </div>
                                <div class="four wide field">
                                    <input type="number" name="zipcode" placeholder="کد پستی" onkeypress='validate_num(event)'>
                                </div>
                            </div>
                            <div class="field">
                                <input type="text" name="address" placeholder="آدرس">
                            </div>
                        </form>
                    </div>
                    <div class="column">
                        <button class="ui left floated button" id="sendNewAddress">ثبت آدرس</button>
                    </div>
                </div>
            </div>
            <div class="ui hidden divider"></div>
        <div class="column">
                        <div class="ui two column grid">
                    <div class="three wide column">
                        <h3>روش پرداخت: </h3>
                    </div>
                    <div class="thirteen wide column">

                                                <div class="ui two column grid">
                    <div class="four wide column">
                              <div class="ui radio checkbox">

        <input name="frequency" type="radio" disabled>
 <label>پرداخت اینترنتی</label>
      </div>
                    </div>
                    <div class="four wide column">
                              <div class="ui radio checkbox">

        <input name="frequency" type="radio" checked>
<label>پرداخت نقدی</label>
      </div>
                    </div>
                </div>


                    </div>
                </div>
        </div>
        <div class="ui hidden divider"></div>
            <div class="column">
                <button class="ui right floated button">بازگشت به صفحه اصلی</button>
                <button class="ui left floated green button" type="submit" disabled id="continue">ادامه</button>
            </div>
        </div>
    </div>

{% endblock %}


{% block scripts %}
    <script src="{% static 'buying/js/order-info.js' %}"></script>
    <script>
        $(document).ready(function() {
            $('.ui.dropdown').dropdown();

            $("#sendNewAddress").click(function(){
            $.post("{% url "buying:add_address" up.id %}", $("#newAddressForm").serialize(), function(data) {
                if (data.stat === 1) {
                    f = $("#newAddressForm");
                    p = f.find("input[name=\"province\"]").val();
                    c = f.find("input[name=\"city\"]").val();
                    a = f.find("input[name=\"address\"]").val();

                    $('<div class="item" data-value="{{ data.add_id }}" style="direction: rtl">'+ p + ' - ' + c + ' - ' + a + '</div>').appendTo($('#addressMenu'));

                    document.getElementById('newAddressForm').reset();
                    document.getElementById('newaddressDiv').style.display = "none";
                    document.getElementById('oldAddresses').style.display = "block";
                }
            });
        });



            $('#addressPlaceHolder').on('DOMSubtreeModified', function() {
                document.getElementById("continue").disabled = false;
            });

            $('#continue').click(function () {
               se = $("input[name=\"selected_address\"]").val();

                $.ajax({
                    url: "{% url 'profiles:set_address' up.id %}",
                    method: 'post',
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        selected_address: se
                    },
                    success: function(data) {
                         window.location.href = data.url;
                    },
                    error: function() {
                        console.error('eeeeerrrrrrooooorrrrrr');
                    }
                })
            });

        });

        function validate_num(evt) {

  var theEvent = evt || window.event;
  var key = theEvent.keyCode || theEvent.which;
  key = String.fromCharCode( key );
  var regex = /[0-9]|[۰-۹]|\.|\t/;
  if( !regex.test(key) && theEvent.keyCode !== 8 && theEvent.keyCode !== 46) {
    theEvent.returnValue = false;
    if(theEvent.preventDefault) theEvent.preventDefault();
  }
}

function showDiv() {
    document.getElementById('newaddressDiv').style.display = "block";
}

</script>
{% endblock %}