Simgun/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

from product.models import Product
from ketabkhor import views


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')


class BookSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Product
        fields = ('isbn', 'title', 'author', 'translator')


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class BookViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = BookSerializer


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'product', BookViewSet)

urlpatterns = [
    url(r'^$', views.home_page, name='home_page'),
    url(r'^admin/', admin.site.urls),
    url(r'^product/', include('product.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^profiles/', include('profiles.urls')),
    url(r'^vendors/', include('vendors.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^premium/', include('premium.urls')),
    url(r'^vendors/', include('vendors.urls')),
    url(r'^orders/', include('buying.urls')),
    url(r'^api/', include(router.urls)),
    url(r'^api/v1/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^support/', include('support.urls'))
]

buying/urls.py
from django.conf.urls import url

from buying import views

app_name = 'buying'

urlpatterns = [
    url(r'(?P<user_id>[0-9]+)/shopping/$', views.order_info, name='order_info'),
    url(r'(?P<user_id>[0-9]+)/addaddress/$', views.add_address, name='add_address'),
    url(r'(?P<user_id>[0-9]+)/removeaddress/(?P<add_id>[0-9]+)/$', views.order_info, name='remove_address'),

    url(r'(?P<user_id>[0-9]+)/getpostprice/$', views.get_post_price, name='get_post_price'),
    url(r'(?P<user_id>[0-9]+)/setpostprice/$', views.set_post_price, name='set_post_price'),
]

profiles/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from profiles import views

app_name = 'profiles'
urlpatterns = [
    url(r'^(?P<profile_id>[0-9]+)/$', login_required(views.profile),
        name='profile'),
    url(r'^(?P<profile_id>[0-9]+)/settings/$', login_required(views.settings),
        name='settings'),
    url(r'^(?P<profile_id>[0-9]+)/upgrade/$', login_required(views.upgrade_user),
        name='upgrade_user'),
    url(r'^(?P<profile_id>[0-9]+)/wishlists/$', login_required(views.wishlist),
        name='wishlist'),

    url(r'^(?P<profile_id>[0-9]+)/shoppingbag/$', login_required(views.shoppingbag),
        name='shoppingbag'),
    url(r'^(?P<profile_id>[0-9]+)/shoppingbag/(?P<bag_id>[0-9]+)/$', login_required(views.shoppingbag_spec),
        name='shoppingbag_spec'),

    url(r'^(?P<profile_id>[0-9]+)/shoppingbag/add/$', login_required(views.add_to_shoppingbag),
        name='add_shoppingbag'),

    url(r'^(?P<profile_id>[0-9]+)/shoppingbag/setaddress/', login_required(views.set_address),
        name='set_address'),
    url(r'^(?P<profile_id>[0-9]+)/shoppingbag/complete/', login_required(views.comp_shopp),
        name='comp_shopping'),
    url(r'^(?P<profile_id>[0-9]+)/shoppingbag/changestate/', login_required(views.shoppingbag_change_state),
        name='shoppingbag_change_state_url'),
    url(r'^(?P<profile_id>[0-9]+)/reviews/$', login_required(views.reviews),
        name='reviews'),
    url(r'^(?P<profile_id>[0-9]+)/reviews/(?P<review_id>[0-9]+)/remove/$', login_required(views.remove_review),
        name='remove_review'),

]

buying/models.py
from django.db import models

from accounts.models import UserProfile, Vendor
from product.models import Product


class PostPrice(models.Model):
    province = models.CharField(max_length=128)
    city = models.CharField(max_length=256)
    vendor = models.ForeignKey(Vendor)
    price = models.IntegerField(default=0)
    type_choices = ((0, 'پست'), (1, 'پیک'))
    type = models.BooleanField(choices=type_choices)

    cities = [
        ['تهران', ['تهران', 'شمیرانات', 'آزادی']],
        ['البرز', ['کرج', 'مصباح ', 'کرج']]
    ]

    def get_type_str(self):
        return self.type_choices[self.type][1]


class Address(models.Model):
    validity = models.BooleanField(default=1)
    province = models.CharField(max_length=128)
    city = models.CharField(max_length=256)
    phone_number = models.IntegerField(default=0)
    zipcode = models.IntegerField(default=0)
    address = models.CharField(max_length=1024)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=True, blank=True)

    def get_full_address(self):
        return str(self.province) + '-' + str(self.city) + '-' + str(self.address)

profiles/models.py
from django.db import models
from accounts.models import UserProfile

from product.models import Product
from buying.models import Address


class Bag(models.Model):
    address = models.ForeignKey(Address, blank=True, null=True)
    date = models.DateTimeField(auto_now=True)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    status = models.IntegerField(choices=((0, 'باز'), (1, 'بسته')), default=0)

    def get_sum_price(self):
        return sum(s.get_sum() for s in self.shoppingbagproduct_set.all() if s.status == 0)


class ShoppingbagProduct(models.Model):
    bag = models.ForeignKey(Bag, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_count = models.IntegerField(default=1)
    price = models.IntegerField(default=0)

    sb_choices = ((-2, 'به دستم نرسیده'), (-1, 'عدمم پشتیبانی شهر'), (0, 'در لیست خرید'), (1, 'سفارش به دست ارائه دهنده رسیده'),
                  (2, 'ارسال شده'), (3, 'به دستم رسیده'))
    status = models.IntegerField(choices=sb_choices, default=0)

    def get_stat(self):
        return self.sb_choices[self.status+2][1]

    def get_sum(self):
        return self.price*self.product_count

profiles/views.py
from django.http import JsonResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User

from django.urls import reverse

from accounts.models import UserProfile
from product.models import Product, Review
from profiles.models import ShoppingbagProduct, Bag
from buying.models import Address

# def add_to_wishlist(request, profile_id):
#     if request.method == 'POST':
#         book_id = request.POST.get('book_id')
#         book = get_object_or_404(Product, pk=book_id)
#         user_profile = get_object_or_404(UserProfile, pk=profile_id)
#         if WishlistBook.objects.filter(user_profile=user_profile, book=book).count() == 0:
#             wishlist_book = WishlistBook(user_profile=user_profile, book=book)
#             wishlist_book.save()
#             return JsonResponse({'status': 'ok'})
#         else:
#             return JsonResponse({'status': 'failure'})


# def remove_from_wishlist(request, profile_id, wishlist_id):
#     if request.method == 'POST':
#         user_profile = get_object_or_404(UserProfile, pk=profile_id)
#         wishlist_book = get_object_or_404(WishlistBook, pk=wishlist_id)
#         wishlist_book.delete()
#         return JsonResponse({'status': 'ok', 'url': reverse('profiles:wishlist', args=(profile_id,))})


# TODO if the book is not available ...
def add_to_shoppingbag(request, profile_id):
    if request.method == 'POST':
        product = get_object_or_404(Product, pk=request.POST.get('book_id'))
        user_profile = get_object_or_404(UserProfile, user=request.user)
        try:
            last_bag = user_profile.bag_set.order_by('-date')[0]
            if last_bag.status == 1:
                last_bag = Bag(user_profile=user_profile)
        except:
            last_bag = Bag(user_profile=user_profile)
        last_bag.save()


        if not last_bag.shoppingbagproduct_set.filter(product=product):
            shoppingbag_product = ShoppingbagProduct(bag=last_bag, product=product, product_count=1, price=product.get_cost())
            shoppingbag_product.save()
            return JsonResponse({'status': 'ok',
                                 'url': reverse('profiles:shoppingbag', args=(profile_id,))
                                 })
        else:
            selected_shoppingbag_product = last_bag.shoppingbagproduct_set.get(product=product)
            selected_shoppingbag_product.product_count += 1
            selected_shoppingbag_product.save()
            return JsonResponse({'status': 'ok',
                                 'url': reverse('profiles:shoppingbag', args=(profile_id,))
                                 })


def shoppingbag(request, profile_id):
    if request.method == 'GET':
        user_profile = get_object_or_404(UserProfile, user=request.user)
        try:
            bags = user_profile.bag_set.all()
        except:
            bags = None
        return render(request, 'profiles/bags.html', {
            'bags': bags,
        })


def shoppingbag_spec(request, profile_id, bag_id):
    if request.method == 'GET':
        user_profile = get_object_or_404(UserProfile, user=request.user)
        try:
            shoppingbags = user_profile.bag_set.get(pk=bag_id)
        except:
            shoppingbags = None

        return render(request, 'profiles/shopping-bag.html', {
            'bag': shoppingbags
        })

def shoppingbag_change_state(request, profile_id):
    if request.method == 'POST':
        print(request.POST)
        sb = ShoppingbagProduct.objects.filter(id=request.POST["bagId"]).first()
        sb.status = request.POST['newstat']
        sb.save()
        return JsonResponse({'success': 1})

# def create_readingprogram(request, profile_id):
#     if request.method == 'POST':
#         book_id = request.POST.get('book_id', -1)
#         if book_id == -1:
#             return JsonResponse({'status': 'failure'})
#         user_profile = get_object_or_404(UserProfile, pk=profile_id)
#         # TODO check for golden User
#         if user_profile.bookreview_set.all().count() > 0:
#             return JsonResponse({
#                 'status': 'failure',
#             })
#         book = get_object_or_404(Product, pk=book_id)
#         reading_program = ReadingProgram(user_profile=user_profile, book=book, current_page=0)
#         reading_program.save()
#         return JsonResponse({
#             'status': 'ok',
#             'url': reverse('profiles:readingprograms', args=(profile_id,))
#         })


# def update_readingprogram(request, profile_id, program_id):
#     if request.method == 'POST':
#         user_profile = get_object_or_404(UserProfile, pk=profile_id)
#         reading_program = get_object_or_404(ReadingProgram, pk=program_id)
#         page_id = int(request.POST.get('current_page', -1))
#         if page_id > reading_program.current_page:
#             reading_program.current_page = page_id
#             reading_program.save()
#             return JsonResponse({
#                 'status': 'ok',
#                 'url': reverse('profiles:readingprograms', args=(profile_id,))
#             })
#         else:
#             return JsonResponse({'status': 'failure'})


def profile(request, profile_id, tab=1):
    user_profile = get_object_or_404(UserProfile, pk=profile_id)
    # reading_programs = user_profile.readingprogram_set.all()
    # favs = user_profile.wishlistbook_set.all()
    # reviews = user_profile.bookreview_set.all()
    return render(request, 'profiles/profile.html', {
        # 'reading_programs': reading_programs,
        # 'favs': favs,
        # 'reviews': reviews,
        'user_profile': user_profile,
        'active_tab': tab,
    })


# def view_readingprogram(request, profile_id, program_id):
#     if request.method == 'GET':
#         user_profile = get_object_or_404(UserProfile, pk=profile_id)
#         reading_program = get_object_or_404(ReadingProgram, pk=program_id)
#         book = reading_program.book
#         return JsonResponse({
#             'status': 'ok',
#             'book_title': book.title,
#             'book_page_count': book.page_count,
#             'book_image': book.pic.url,
#             'current_page': reading_program.current_page,
#         })
#     else:
#         return JsonResponse({
#             'status': 'failure'
#         })
#
#
# def remove_readingprogram(request, profile_id, program_id):
#     user_profile = get_object_or_404(UserProfile, pk=profile_id)
#     reading_program = get_object_or_404(ReadingProgram, pk=program_id)
#     reading_program.delete()
#     return JsonResponse({'status': 'ok', 'url': reverse('profiles:readingprograms', args=(profile_id,))})


def set_address(request, profile_id):
    if request.method == 'POST':
        address = get_object_or_404(Address, pk=request.POST.get('selected_address'))
        user_profile = get_object_or_404(UserProfile, user=request.user)

        try:
            last_bag = user_profile.bag_set.order_by('-date')[0]
            if last_bag.status == 0:
                last_bag.address = address
                last_bag.save()
                for sb in last_bag.shoppingbagproduct_set.all():
                    if sb.product.productvendor_set.first().vendor.postprice_set.filter(province=address.province, city=address.city).count() == 0:
                        sb.status = -1
                        sb.save()
            return JsonResponse({'success': 1, 'url': reverse('profiles:shoppingbag_spec', args=(profile_id, last_bag.id))})


        except:
            return JsonResponse({'success': 1, 'url': reverse('profiles:shoppingbag', args=(profile_id, ))})




def comp_shopp(request, profile_id):
    if request.method == 'POST':
        user_profile = get_object_or_404(UserProfile, user=request.user)

        try:
            last_bag = user_profile.bag_set.order_by('-date')[0]
            if last_bag.status == 0:
                last_bag.status = 1
                last_bag.save()
                address = last_bag.address
                for sb in last_bag.shoppingbagproduct_set.all():
                    if sb.product.productvendor_set.first().vendor.postprice_set.filter(province=address.province, city=address.city).count() == 0:
                        sb.status = -1

                    else:
                        sb.status = 1
                    sb.save()
            return JsonResponse({'success': 1})


        except:
            return JsonResponse({'success': 1})




def wishlist(request, profile_id):
    if request.method == 'GET':
        return profile(request, profile_id, 1)


# def readingprograms(request, profile_id):
#     if request.method == 'GET':
#         return profile(request, profile_id, 2)


def reviews(request, profile_id):
    if request.method == 'GET':
        return profile(request, profile_id, 3)


def remove_review(request, profile_id, review_id):
    user_profile = get_object_or_404(UserProfile, pk=profile_id)
    review = get_object_or_404(Review, pk=review_id)
    review.delete()
    print(reverse('profiles:reviews', args=(profile_id,)))
    return JsonResponse({'status': 'ok', 'url': reverse('profiles:reviews', args=(profile_id,))})


# def remove_wishlist_book(request, profile_id):
#     if request.method == 'POST':
#         user_profile = get_object_or_404(UserProfile, pk=profile_id)
#         book_id = request.POST.get('book_id', -1)
#         if book_id == -1:
#             return JsonResponse({'status': 'failure'})
#         book = get_object_or_404(Product, pk=book_id)
#         wishlist = get_object_or_404(WishlistBook, user_profile=user_profile, book=book)
#         wishlist.delete()
#         return JsonResponse({'status': 'ok', 'url': reverse('profiles:wishlist', args=(profile_id,))})


def settings(request, profile_id):
    user_profile = get_object_or_404(UserProfile, pk=profile_id)
    if request.method == 'GET':

templates/profiles/bags.html
{% extends 'simgun/base.html' %}

{% block styles %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'profiles/css/style-shopping-cart.css' %}"/>
{% endblock %}


{% block title %}
    <title>زنبیل - سبد خرید </title>
{% endblock %}

{% block content %}

    <div class="ui container">
        <div class="ui grid container center aligned">
            <div class="eleven wide column right aligned back-grey container-offset">
                <div class="ui grid container">
                    <div class="ui row">
                        <div class="center column center aligned">
                            <h4 class="ui header font-normal">سبدهای خرید</h4>
                        </div>
                    </div>
                    <div class="ui row">
                        <table class="ui celled structured table">
                            <thead class="back-grey-dark">
                            <tr>
                                <th>تاریخ</th>
                                <th>مجموع قیمت(تومان)</th>
                                <th>وضعیت</th>
                                <th>ویرایش</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for b in bags %}
                                <tr class="bottom-line">
                                    <td>{{ b.date }}</td>
                                    <td>{{ b.get_sum_price }}</td>
                                    {% if b.status %}
                                    <td>بسته</td>
                                    {% else %}
                                    <td>باز</td>
                                    {% endif %}

                                    <td><a href="{% url 'profiles:shoppingbag_spec' user.id b.id %}"><i class="linkify icon"></i></a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
{#                    <div class="ui row">#}
{#                        <div class="ui grid container">#}
{#                            <div class="eight wide column right aligned">#}
{#                                <button  id="return-btn" class="ui button">بازگشت به صفحه اصلی</button>#}
{#                            </div>#}
{#                            <div class="eight wide column left aligned">#}
{#                                <button id="continue-btn" class="ui primary button">وارد کردن مشخصات</button>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block scripts %}
{#    <script>#}
{#        $(function(){#}
{#            $('[id^=book-count]').each(function(i) {#}
                {#            console.log({{ shoppingbags }});#}
{#                var data = {{ shoppingbags }}#}
{#                    console.log(data)#}
{#            });#}
{#            $('[id^=book-price-mul-count]').each(function(i){#}
{#                var count = parseInt($('#book-count' + i).find(':selected').text());#}
{#                console.log(count);#}
{#            });#}
{##}
{#            $('#return-btn').click(function() {#}
{#                window.location.href = '/'#}
{#            });#}
{##}
{#            $('#continue-btn').click(function() {#}
{#                window.location.href = "{% url 'buying:order_info' user.id %}"#}
{#            })#}
{#        });#}
{#    </script>#}
{% endblock %}

templates/profiles/premium-membership.html
{% extends 'simgun/base.html' %}

{% block title %}
    <title>ارتقا به کاربر طلایی</title>
{% endblock %}


{% block styles %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'profiles/css/style-permium.css' %}"/>
{% endblock %}


{% block content %}
    <div class="ui container con-margin page-wrap">
        <div class="ui grid container">
            <div class="two wide column"></div>
            <div class="twelve wide column left aligned premium-grey box-shadow">
                <div >
                    <a class="ui orange ribbon label"> پیشنهاد ویژه</a>
                </div>
                <div class="ui grid center aligned">
                    <div class="sixteen wide column">
                        <img src="{% static 'site-media/photos/general/anchoochak.png' %}">
                        <h1 class="ui font-header">ارتقا به کاربر طلایی </h1>
                        <h3 class="ui grey header">استفاده از خدمات دریافت کتاب رقمی</h3>
                        <h3 class="ui grey header">استفاده از خدمات دریافت کتاب صوتی</h3>
                        <h3 class="ui grey header">امکان اضافه کردن چندین برنامه مطالعاتی</h3>
                        <div class="ui divider"></div>
                        <button class="ui inverted orange button">ارتقا حساب</button>
                        <h4 class="ui light-orange header">فقط برای 9900 تومان / 3 ماه</h4>
                    </div>
                </div>

            </div>
            <div class="two wide column"></div>
        </div>
    </div>

{% endblock %}


{% block scripts %}

{% endblock %}

templates/profiles/shopping-bag.html
{% extends 'simgun/base.html' %}

{% block styles %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'profiles/css/style-shopping-cart.css' %}"/>
{% endblock %}


{% block title %}
    <title>زنبیل - سبد خرید </title>
{% endblock %}

{% block content %}

    <div class="ui container">
        <div class="ui grid container center aligned">
            <div class="eleven wide column right aligned back-grey container-offset">
                <div class="ui grid container">
                    <div class="ui row">
                        <div class="center column center aligned">
                            <h4 class="ui header font-normal">سبد خرید</h4>
                        </div>
                    </div>
                    <div class="ui row">
                        <table class="ui celled structured table">
                            <thead class="back-grey-dark">
                            <tr>
                                <th>عنوان</th>
                                <th>قیمت واحد(تومان)</th>
                                <th>تعداد</th>
                                <th>قیمت اجناس</th>
                                <th>هزینه ارسال</th>
                                <th>هزینه نهایی</th>
{#                                <th>اضافه</th>#}
{#                                <th>حذف</th>#}
                                <th>وضعیت</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for sb in bag.shoppingbagproduct_set.all %}
                                <tr class="bottom-line sb">
                                    <td class="b-title">{{ sb.product }}</td>
                                    <td class="b-price">{{ sb.price }}</td>
                                    <td class="b-count">{{ sb.product_count }}</td>
                                    <td class="b-cost">{{ sb.get_sum }}</td>
                                    <td class="b-send-type">
                                        <select class="ui dropdown stype">
                                            {% for t in sb.product.productvendor_set.first.vendor.postprice_set.all %}
                                                <option value="{{ t.type }}:{{ t.price }}" data-value="{{ t.price }}">{{ t.get_type_str }} : {{ t.price }}</option>
                                            {% endfor %}

                                        </select>






                                    </td>
                                    <td class="b-sum">
                                        {% if sb.stat == -1 or not sb.product.productvendor_set.first.vendor.postprice_set.first.price %}
                                        0
                                            {% else %}
                                            {{ sb.get_sum|add:sb.product.productvendor_set.first.vendor.postprice_set.first.price }}
                                        {% endif %}
                                    </td>
{#                                     </td>#}
{#                                    <td>#}
{##}
{##}
{#                                    </td>#}
{#                                    <td>-</td>#}
                                <td class="b-stat">{{  sb.get_stat}}</td>
                                </tr>
                            {% endfor %}
{#                            <tr class="empty-col">#}
{#                                <td class="empty-col"></td>#}
{#                                <td class="empty-col"></td>#}
{#                                <td class="empty-col"></td>#}
{#                                <td class="empty-col"></td>#}
{#                                <td class="empty-col"></td>#}
{#                                <td class="empty-col"></td>#}
{##}
{#                                <td colspan="3" class="right aligned white-bg">جمع کل خرید شما: {{ bag.get_sum_price }}</td>#}
{#                            </tr>#}
                            <tr class="empty-col">
                                <td class="empty-col"></td>
                                <td class="empty-col"></td>
                                <td class="empty-col"></td>
                                <td class="empty-col"></td>

                                <td colspan="3" class="right aligned pay-box-bg pay-box-border">مبلغ قابل پرداخت: {{ bag.get_sum_price }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="ui row">
                            <div class="ui grid container">

                                <div class="ui two column grid" style="display: inline">
                                    <div class="four wide column" style="display: inline-block">
                                        <h3>آدرس انتخاب شده: </h3>
                                    </div>
                                    <div class="twelve wide column" style="display: inline-block">
                                        {% if bag.address %}
                                        <p> {{ bag.address.get_full_address }}</p>
                                        {% else %}
                                        <p> آدرسی انتخاب نشده است. لطفا درر قسمت ویرایش اطلاعات آدرسی را انتخاب کنید</p>
                                        {% endif %}
                                    </div>
                                </div>

                            </div>
                    </div>
                        <div class="ui row">
                        <div class="ui grid container">
                            <div class="eight wide column right aligned">
                                <button  id="return-btn" class="ui button" href="{% url 'profiles:shoppingbag' user.id %}">بازگشت به صفحه اصلی</button>
                            </div>

                            <div class="four wide column left aligned">
                                <button id="continue-btn" class="ui primary button">ویرایش اطلاعات</button>
                            </div>
                            <div class="four wide column left aligned">
                            {% if bag.status == 0 %}
                                <button id="buy-btn" class="ui secondary button"
                                        {% if not bag.address %}

                                            disabled
                                        {% endif %}

                                >خرید</button>
                            {% else %}
                                <button id="buy-btn" class="ui secondary button"
                                            disabled
                                >خرید انجام شده است</button>
                            {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block scripts %}
    <script>

    $(document).ready(function () {
         $('.ui.dropdown').dropdown();


                     $('#buy-btn').click(function () {

                    var typeArray = $(".stype").map(function() {return $(this).val()}).get();
                    console.log(typeArray);
                $.ajax({
                    url: "{% url 'profiles:comp_shopping' user.id %}",
                    method: 'post',
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
{#                        selected_address: se#}
                    },
                    success: function(data) {
                         window.location.href = '/';
                    },
                    error: function() {
                        console.error('eeeeerrrrrrooooorrrrrr');
                    }
                })
            });

    });
        $(function(){
            $('[id^=book-count]').each(function(i) {
                            console.log({{ shoppingbags }});
{#                var data = {{ shoppingbags }}#}
{#                    console.log(data)#}
            });
            $('[id^=book-price-mul-count]').each(function(i){
                var count = parseInt($('#book-count' + i).find(':selected').text());
                console.log(count);
            });

            $('#return-btn').click(function() {
                window.location.href = '/'
            });

            $('#continue-btn').click(function() {
                window.location.href = "{% url 'buying:order_info' user.id %}"
            })
        });


        function new_sum() {


        }

        $('.stype').on('change', function() {
            ele = $(this).closest("td[class='b-send-type']");
            send_price = $(this).val().split(":")[1];
            cost = ele.prev().html();
            ele.next().html(parseInt(send_price) + parseInt(cost));
            new_sum();
        });



    </script>
{% endblock %}